export enum BookingStatus {
  NEW = "NEW",
  CONFIRMED = "CONFIRMED",
  OUT_OF_DATE = "OUT_OF_DATE",
  COMPELETED = "COMPLETED",
  CANCELED = "CANCELED",
  PROCESSING = "PROCESSING",
}

export enum BookingTypes {
  EXAMINATION = "EXAMINATION",
  RE_EXAMINATION = "RE_EXAMINATION",
  CONSULTATION = "CONSULTATION",
}
